### ISSUE TITLE
process large equirectangular

### ISSUE THREAD

**Issue by CorentinLemaitre** [BlueHorn07/pyEquirectRotate#1]
Hello, 

First thank you for your code to process equirectangular with python. I acheive to make the demo work but when i try to use the code with my own file it do it really slowly.

I share with you a large file to make it easier to try : 
![some_image](https://user-images.githubusercontent.com/20289907/125944292-39936e3e-dfe8-45a8-a324-a38f584f678f.jpg)

Is there any way to make the process quicker ?

**Comment by BlueHorn07** [comment]
Hi @CorentinLemaitre. Thanks for your attension 😄 

I downloaded your file, and it was 5 MB! (That's huge!)

Because of the rotating procedure, the larger file makes process slower. 😢 

My code provide the rotator as a `class`, so you can re-use that instance! This means in the first time it takes some time, but you can process a bunch of files with fewer latency! [code link](https://github.com/BlueHorn07/pyEquirectRotate/blob/main/src/demo.py#L15)

The another solution is to save the mapping array `self.src_Pixel` as `.npy` file. [code link](https://github.com/BlueHorn07/pyEquirectRotate/blob/main/src/equirectRotate/EquirectRotate.py#L39) This method will reduce the first delay of the rotating. You can do this with little customization using `numpy.save()` and `numpy.load()`. Notice that this method works only use the same rotating angle and same input image size. 

I hope these solutions will help you 🙏  and have a nice day 👍

**Comment by CorentinLemaitre** [comment]
Thank you very  much for the test and answer. The latency is not due to any misconfiguration or bug, but it is just the limit of the program. 
Thank for the advice to divide by two the processing time.
